name: Mirror Status Check

on:
  schedule:
    # 30분마다 실행
    - cron: '*/30 * * * *'
  # 저장소에 변경 사항이 푸시될 때 실행
  push:
    branches:
      - main
  # 수동 실행 옵션
  workflow_dispatch:

jobs:
  check-mirrors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run mirror check
        run: ./rokfoss-checker